[versions]
bouncycastle = "1.70"
feign = "12.1"
grpc = "1.51.1"
jackson = "2.14.1"
jackson-protobuf = "0.9.13"
kotlin = "1.9.10"
protobuf = "3.21.12"
provenance-client = "2.4.0-rc1"
provenance-hdwallet = "0.1.15"
provenance-proto = "1.13.0"
provenance-scope = "0.6.2"

[libraries]
bouncycastle = { module = "org.bouncycastle:bcprov-jdk15on", version.ref = "bouncycastle" }
feign-jackson = { module = "io.github.openfeign:feign-jackson", version.ref = "feign" }
grpc-netty = { module = "io.grpc:grpc-netty", version.ref = "grpc" }
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
jackson-datatype-jdk8 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-module-protobuf = { module = "com.hubspot.jackson:jackson-datatype-protobuf", version.ref = "jackson-protobuf" }
kotlin-allopen = { module = "org.jetbrains.kotlin:kotlin-allopen", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protobuf-java-util = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protobuf" }
provenance-client = { module = "io.provenance.client:pb-grpc-client-kotlin", version.ref = "provenance-client" }
provenance-hdwallet = { module = "io.provenance.hdwallet:hdwallet", version.ref = "provenance-hdwallet" }
provenance-proto = { module = "io.provenance:proto-kotlin", version.ref = "provenance-proto" }
provenance-scope-encryption = { module = "io.provenance.scope:encryption", version.ref = "provenance-scope" }
provenance-scope-objectstore-client = { module = "io.provenance.scope:os-client", version.ref = "provenance-scope" }
provenance-scope-util = { module = "io.provenance.scope:util", version.ref = "provenance-scope" }

[bundles]
grpc = ["grpc-netty", "grpc-netty-shaded", "grpc-protobuf", "grpc-stub"]
jackson = ["jackson-datatype-jdk8", "jackson-datatype-jsr310", "jackson-module-kotlin", "jackson-module-protobuf"]
kotlin = ["kotlin-allopen", "kotlin-reflect", "kotlin-stdlib-jdk8"]
protobuf = ["protobuf-java", "protobuf-java-util"]
provenance = ["provenance-client", "provenance-hdwallet", "provenance-proto", "provenance-scope-encryption", "provenance-scope-util"]
